#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "775e8a7c90ec4b66b794787809789e08"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "bae64391cf1c4097ae7533e4159825be"
preview_database_id = "f591d1c7-0060-4d35-a146-099ec27b49b1"
migrations_dir = "app/drizzle"
